### ISSUE TITLE
Packet is blocked when opening form

### ISSUE THREAD

**Issue by jacob3105** [GabBiswajit/ImageLoader#1]
- Like title

**Comment by GabBiswajit** [comment]
This issue was not with me, Can you give a screenshot?

**Comment by GabBiswajit** [comment]
Hey @jacob3105 This Issue Not With Image Loader It's Because Your Texture Packs Or Any Other Plugins.

**Comment by 0xliam627** [comment]
> Hey @jacob3105 This Issue Not With Image Loader It's Because Your Texture Packs Or Any Other Plugins.

Can you explain why texture packs are involved? @GabBiswajit
